### ISSUE TITLE
Kanban project setup

### ISSUE THREAD

**Issue by ismayito** [ismayito/Rails-recipe-app#18]
[kanban project](https://github.com/users/ismayito/projects/3/views/1?template_dialog_tab=featured&filterQuery=assignee%3Aismayito)
Hello reviewer I have been allowed by microverse to week alone for the rest of this week as there are no people in the same week as I am.

**Comment by gemmen29** [comment]
Hi @ismayito, 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!

## Highlights 💯 
- Descriptive info ✔️ 

![](https://media.giphy.com/media/tKyrc0NTlEcGWdThp4/giphy.gif)

## Required Changes ♻️
- ### Kindly add a description for the following tasks:
   - [ ] https://github.com/ismayito/Rails-recipe-app/issues/6
   - [ ] https://github.com/ismayito/Rails-recipe-app/issues/7
   - [ ] https://github.com/ismayito/Rails-recipe-app/issues/9
   - [ ] https://github.com/ismayito/Rails-recipe-app/issues/10
   - [ ] https://github.com/ismayito/Rails-recipe-app/issues/11
   - [ ] https://github.com/ismayito/Rails-recipe-app/issues/12
   - [ ] https://github.com/ismayito/Rails-recipe-app/issues/13
   - [ ] https://github.com/ismayito/Rails-recipe-app/issues/14
   - [ ] https://github.com/ismayito/Rails-recipe-app/issues/15
   - [ ] https://github.com/ismayito/Rails-recipe-app/issues/16
   - [ ] https://github.com/ismayito/Rails-recipe-app/issues/17
   
 as per this [requirement](https://github.com/microverseinc/curriculum-rails/blob/main/recipe-app/setup_kanban_board.md#:~:text=Has%20a%20description%20of%20the%20task.). Every task should have a description.

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Comment by IngDavidTM** [comment]
Hi @ismayito 🙋‍♂️, 

# ✔️   Status: APPROVED 🏆 🎉 🎊 

You have done a great job setting up your Kanban project, keep it up 👍 🥇.
Congratulations!  🎉💯🌟 

## Top highlight 🎯

- The cards were created successfully ✅ 
<img src="https://media3.giphy.com/media/xT0xezQGU5xCDJuCPe/giphy.gif"/>

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._
